### ISSUE TITLE
Font Awesome 6

### ISSUE THREAD

**Issue by daveyjones** [FortAwesome/react-native-fontawesome#110]
Any idea when Font Awesome 6 icons will be available in this library?

**Comment by vincentzierigen** [comment]
Interested as well

**Comment by mlwilkerson** [comment]
The icons themselves are pulled in via separate NPM packages, like `@fortawesome/free-solid-svg-icons` or `@fortawesome/pro-solid-svg-icons`. I _think_ the v6 NPMs should work the same as the v5 ones.

**Comment by christianrank** [comment]
Just upgraded the fontawesome packages to 6. There comes a warning, not sure what it means but it looks like everything is working.

```
$ react-native run-ios --scheme Dev --configuration Dev.Debug
warn Package @fortawesome/free-brands-svg-icons has been ignored because it contains invalid configuration. Reason: Cannot find module '/.../node_modules/@fortawesome/free-brands-svg-icons/package.json.js'
warn Package @fortawesome/pro-duotone-svg-icons has been ignored because it contains invalid configuration. Reason: Cannot find module '/.../node_modules/@fortawesome/pro-duotone-svg-icons/package.json.js'
warn Package @fortawesome/pro-light-svg-icons has been ignored because it contains invalid configuration. Reason: Cannot find module '/.../node_modules/@fortawesome/pro-light-svg-icons/package.json.js'
warn Package @fortawesome/pro-regular-svg-icons has been ignored because it contains invalid configuration. Reason: Cannot find module '/.../node_modules/@fortawesome/pro-regular-svg-icons/package.json.js'
warn Package @fortawesome/pro-solid-svg-icons has been ignored because it contains invalid configuration. Reason: Cannot find module '/.../node_modules/@fortawesome/pro-solid-svg-icons/package.json.js'
```

**Comment by christianrank** [comment]
Somehow it seems to work only in the dev build. When I try to create a production build, the build process runs forever. (No error, it just never finishes.)

Any ideas?

**Comment by ajstokar** [comment]
import {faThumbtack as faThumbtackLight} from '@fortawesome/pro-light-svg-icons/faThumbtack';
import {faThumbtack as faThumbtackSolid} from '@fortawesome/pro-solid-svg-icons/faThumbtack';

These imports aren't working with the react-native library.  Haven't had a problem with any others besides this.

**Comment by RayHughes** [comment]
Has any one gotten this to work yet? I am also experiencing build warnings about being unable to locate the packages

**Comment by indigomelody** [comment]
i have this issue too. Fixed using deep imports, but would like the error out of my terminal and to not have to use deep imports each time. Any updates on a fix for this?

**Comment by robmadole** [comment]
I've updated the documentation on the README https://github.com/FortAwesome/react-native-fontawesome#i-dont-think-tree-shaking-is-working-got-any-advice

@ajstokar are you still having issues?

**Comment by foxfl** [comment]
Facing a similar issue with v6 Icons. We changed all imports to use "deep imports" like 
`import { faFileChartLine } from '@fortawesome/pro-light-svg-icons/faFileChartLine';` 

This resolved the build issue on android for us. Still, the build time is up to 40 minutes (compared to twelve minutes before) and iOS build on Expo EAS is running in a timeout after 45 minutes. 

Is there going to be an update to the library or are there any other things we can do to fix this and bring down build time?

Also, importing icons as documented [in the three-shaking section](https://github.com/FortAwesome/react-native-fontawesome#i-dont-think-tree-shaking-is-working-got-any-advice) is not working. 
This: `import faStroopwafel from '@fortawesome/pro-solid-svg-icons/faStroopwafel'` results in `ERROR: icon not found for icon = , null`

**Comment by robmadole** [comment]
@foxfl sorry about that. We were missing the curly brackets for that import. I've corrected the README.md so can you try:

```
import { faStroopwafel } from '@fortawesome/pro-solid-svg-icons/faStroopwafel'
```

If you change all imports to the deep imports it should bring your build time down to the expected time.

**Comment by adrygll** [comment]
Any plans to add support for [FontAwesome Kits](https://fontawesome.com/v6/docs/web/setup/use-kit)?

**Comment by foxfl** [comment]
Hi @robmadole, 

Thanks for updating the docs! :) 

We changed all the imports to use deep imports but still facing the same issue. We are running EAS builds on Expo. In development mode, everything works fine (we are using our own development client). But as soon as we try to build with icons from V6, we are facing really long build times as described in the other comment. Downgrading the icon packages to V5 reduced the build time to about 15 minutes for each platform.

Do you have any idea what can cause this or are we missing anything else that needs to be changed? 
The problem with EAS builds is that they cannot run locally, so it's hard for me to debug without wasting our build minutes here.

**Comment by robmadole** [comment]
@foxfl I'm not sure. If you can provide a reproducible repo I can take a look.

**Comment by robmadole** [comment]
All we have just released 0.3.0 which should fully support Font Awesome 6. Please give it a try if you have time and let us know if anything looks awry. We will also be deploying some documentation updates to fontawesome.com in the next few days.

@foxfl also, if you could create a separate issue that would be great. This original topic was about FA 6 which with the release of 0.3.0 we fully support.
